In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('csv/reserve.csv', skiprows=12, sep=';', encoding='ISO-8859-1')
df.head(32)

,Compte,Date de comptabilisation,Numéro d'extrait,Numéro de transaction,Compte contrepartie,Nom contrepartie contient,Rue et numéro,Code postal et localité,Transaction,Date valeur,Montant,Devise,BIC,Code pays,Communications
0,BE92 0882 7323 2423,17/09/2025,16,134,BE59 0635 8306 6126,Dodevski - Dodevska,AV HENRI LIEBRECHT 88/1,1090 BRUXELLES,VERSEMENT INSTANTANE DE BE59 0635 8306 6126 Do...,16/09/2025,"38,47",EUR,GKCCBEBB,BE,DODEVSKI DODEVSKA 07D G5
1,BE92 0882 7323 2423,12/09/2025,16,133,BE69 0018 7141 9178,LAMAASSAB LOTFI,RUE FRANS ROBBRECHTS 23,1780 WEMMEL,VERSEMENT DE BE69 0018 7141 9178 LAMAASSAB LOT...,13/09/2025,"43,40",EUR,GEBABEBB,BE,+++787/3088/12694+++
2,BE92 0882 7323 2423,09/09/2025,16,132,BE53 7775 9906 9753,MACHIELS DANNY,HENRI LIBRECHTLAAN 88/7G/L,1090 JETTE,VERSEMENT DU BE53 7775 9906 9753 MACHIELS DANN...,10/09/2025,"43,40",EUR,GKCCBEBB,BE,reservefonds ACP Jupiter #0840.357.619
3,BE92 0882 7323 2423,08/09/2025,16,131,BE03 6115 4250 3084,Mme Coumont Marie France,AV. HENRI LIEBRECHT 88 6GL,1090 JETTE,VERSEMENT DE BE03 6115 4250 3084 Mme Coumont M...,09/09/2025,"43,40",EUR,DEUTBEBE,BE,+++121/9258/59624+++
4,BE92 0882 7323 2423,04/09/2025,16,130,BE16 7360 3283 5574,BADOT PIERRE,AV. HENRI LIEBRECHT 88,1090 JETTE,VERSEMENT DE BE16 7360 3283 5574 BADOT PIERRE ...,05/09/2025,"85,78",EUR,KREDBEBB,BE,+++544/3098/07514+++
5,BE92 0882 7323 2423,04/09/2025,16,129,BE85 2100 8750 8806,MOLDEREZ JEAN FRANCOIS EMI,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE85 2100 8750 8806 MOLDEREZ JEAN...,05/09/2025,"35,00",EUR,GEBABEBB,BE,ACP Jupiter Fonds Reserve - Acompte Mensuel (M...
6,BE92 0882 7323 2423,03/09/2025,16,128,BE47 9733 9672 4980,NICULESCU - NICULESCU,AVENUE HENRI LIEBRECHT 88/3d r,1090 JETTE,VERSEMENT INSTANTANE DE BE47 9733 9672 4980 NI...,03/09/2025,"35,44",EUR,ARSPBE22,BE,+++515/9340/01329+++
7,BE92 0882 7323 2423,03/09/2025,16,127,BE70 0630 0327 7625,Raveyts Annie,PUURSESTEENWEG 204,2880 BORNEM,VERSEMENT DU BE70 0630 0327 7625 Raveyts Annie...,04/09/2025,"35,44",EUR,GKCCBEBB,BE,+++174/8037/33241+++
8,BE92 0882 7323 2423,02/09/2025,15,126,BE62 0634 2042 9761,Vanvulescu Causette,AV HENRI LIEBRECHT 88/9,1090 JETTE,VERSEMENT INSTANTANE DE BE62 0634 2042 9761 Va...,02/09/2025,"43,40",EUR,GKCCBEBB,BE,+++523/3226/76235+++
9,BE92 0882 7323 2423,02/09/2025,15,125,BE83 2100 8708 2915,BOURGEOIS NANCY VALENTINE,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE83 2100 8708 2915 BOURGEOIS NAN...,03/09/2025,"35,44",EUR,GEBABEBB,BE,+++964/8104/47052+++
10,BE92 0882 7323 2423,02/09/2025,15,124,BE58 1430 7889 7679,MAIGRET-PAILOS FERNANDEZ,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE58 1430 7889 7679 MAIGRET-PAILO...,03/09/2025,"43,40",EUR,GEBABEBB,BE,+++381/2316/20589+++
11,BE92 0882 7323 2423,02/09/2025,15,123,BE14 0613 7230 6083,MATTELAER NICOLE,AV HENRI LIEBRECHT 88/15,1090 BRUXELLES,VERSEMENT DU BE14 0613 7230 6083 MATTELAER NIC...,03/09/2025,"85,78",EUR,GKCCBEBB,BE,472/5733/42023
12,BE92 0882 7323 2423,01/09/2025,15,122,BE38 0013 2929 5272,LEFEVRE NICOLAS,Av.H.Liebrecht 88 7,1090 JETTE,VERSEMENT INSTANTANE DE BE38 0013 2929 5272 LE...,01/09/2025,"31,42",EUR,GEBABEBB,BE,609724853733
13,BE92 0882 7323 2423,01/09/2025,15,121,BE81 7340 0026 3424,JUPITER BV,BIESBOSLAAN 13,1785 HAMME (BRABANT),VERSEMENT DE BE81 7340 0026 3424 JUPITER BV ...,02/09/2025,"70,88",EUR,KREDBEBB,BE,+++722/6400/01522+++
14,BE92 0882 7323 2423,18/08/2025,15,120,BE59 0635 8306 6126,Dodevski - Dodevska,AV HENRI LIEBRECHT 88/1,1090 BRUXELLES,VERSEMENT INSTANTANE DE BE59 0635 8306 6126 Do...,18/08/2025,"38,47",EUR,GKCCBEBB,BE,DIDEVSKI DODEVSKA 07D G5
15,BE92 0882 7323 2423,12/08/2025,14,119,BE69 0018 7141 9178,LAMAASSAB LOTFI,RUE FRANS ROBBRECHTS 23,1780 WEMMEL,VERSEMENT DE BE69 0018 7141 9178 LAMAASSAB LOT...,13/08/2025,"43,40",EUR,GEBABEBB,BE,+++787/3088/12694+++
16,BE92 0882 7323 2423,11/08/2025,14,118,BE53 7775 9906 9753,MACHIELS DANNY,HENRI LIBRECHTLAAN 88/7G/L,1090 JETTE,VERSEMENT DU BE53 7775 9906 9753 MACHIELS DANN...,12/08/2025,"43,40",EUR,GKCCBEBB,BE,reservefonds ACP Jupiter #0840.357.619
17,BE92 0882 7323 2423,06/08/2025,14,117,BE47 9733 9672 4980,NICULESCU - NICULESCU,AVENUE HENRI LIEBRECHT 88/3d r,1090 JETTE,VERSEMENT INSTANTANE DE BE47 9733 9672 4980 NI...,06/08/2025,"35,44",EUR,ARSPBE22,BE,+++515/9340/01329+++
18,BE92 0882 7323 2423,06/08/2025,14,116,BE03 6115 4250 3084,Mme Coumont Marie France,AV. HENRI LIEBRECHT 88 6GL,1090 JETTE,VERSEMENT DE BE03 6115 4250 3084 Mme Coumont M...,07/08/2025,"43,40",EUR,DEUTBEBE,BE,+++121/9258/59624+++
19,BE92 0882 7323 2423,05/08/2025,14,115,BE85 2100 8750 8806,MOLDEREZ JEAN FRANCOIS EMI,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE85 2100 8750 8806 MOLDEREZ JEAN...,06/08/2025,"35,00",EUR,GEBABEBB,BE,ACP Jupiter Fonds Reserve - Acompte Mensuel (M...
20,BE92 0882 7323 2423,04/08/2025,14,114,BE62 0634 2042 9761,Vanvulescu Causette,AV HENRI LIEBRECHT 88/9,1090 JETTE,VERSEMENT INSTANTANE DE BE62 0634 2042 9761 Va...,04/08/2025,"43,40",EUR,GKCCBEBB,BE,+++523/3226/76235+++
21,BE92 0882 7323 2423,04/08/2025,14,113,BE16 7360 3283 5574,BADOT PIERRE,AV. HENRI LIEBRECHT 88 B11,1090 JETTE,VERSEMENT DE BE16 7360 3283 5574 BADOT PIERRE ...,05/08/2025,"85,78",EUR,KREDBEBB,BE,+++544/3098/07514+++
22,BE92 0882 7323 2423,04/08/2025,14,112,BE83 2100 8708 2915,BOURGEOIS NANCY VALENTINE,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE83 2100 8708 2915 BOURGEOIS NAN...,05/08/2025,"35,44",EUR,GEBABEBB,BE,+++964/8104/47052+++
23,BE92 0882 7323 2423,04/08/2025,14,111,BE38 0013 2929 5272,LEFEVRE NICOLAS,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE38 0013 2929 5272 LEFEVRE NICOL...,05/08/2025,"31,42",EUR,GEBABEBB,BE,+++609/7248/53733+++
24,BE92 0882 7323 2423,04/08/2025,14,110,BE58 1430 7889 7679,MAIGRET-PAILOS FERNANDEZ,Av.H.Liebrecht 88,1090 JETTE,VERSEMENT DE BE58 1430 7889 7679 MAIGRET-PAILO...,05/08/2025,"43,40",EUR,GEBABEBB,BE,+++381/2316/20589+++
25,BE92 0882 7323 2423,04/08/2025,14,109,BE70 0630 0327 7625,Raveyts Annie,PUURSESTEENWEG 204,2880 BORNEM,VERSEMENT DU BE70 0630 0327 7625 Raveyts Annie...,05/08/2025,"35,44",EUR,GKCCBEBB,BE,+++174/8037/33241+++
26,BE92 0882 7323 2423,04/08/2025,14,108,BE14 0613 7230 6083,MATTELAER NICOLE,AV HENRI LIEBRECHT 88/15,1090 BRUXELLES,VERSEMENT DU BE14 0613 7230 6083 MATTELAER NIC...,05/08/2025,"85,78",EUR,GKCCBEBB,BE,472/5733/42023
27,BE92 0882 7323 2423,01/08/2025,14,107,BE81 7340 0026 3424,JUPITER BV,BIESBOSLAAN 13,1785 HAMME (BRABANT),VERSEMENT DE BE81 7340 0026 3424 JUPITER BV ...,02/08/2025,"70,88",EUR,KREDBEBB,BE,+++722/6400/01522+++
28,BE92 0882 7323 2423,15/07/2025,13,106,BE59 0635 8306 6126,Dodevski - Dodevska,AV HENRI LIEBRECHT 88/1,1090 BRUXELLES,VERSEMENT INSTANTANE DE BE59 0635 8306 6126 Do...,15/07/2025,"38,47",EUR,GKCCBEBB,BE,DODEVSKI DODEVSKA 7DR 05G
29,BE92 0882 7323 2423,14/07/2025,13,105,BE69 0018 7141 9178,LAMAASSAB LOTFI,RUE FRANS ROBBRECHTS 23,1780 WEMMEL,VERSEMENT DE BE69 0018 7141 9178 LAMAASSAB LOT...,15/07/2025,"43,40",EUR,GEBABEBB,BE,+++787/3088/12694+++
30,BE92 0882 7323 2423,09/07/2025,13,104,BE53 7775 9906 9753,MACHIELS DANNY,HENRI LIBRECHTLAAN 88/7G/L,1090 JETTE,VERSEMENT DU BE53 7775 9906 9753 MACHIELS DANN...,10/07/2025,"43,40",EUR,GKCCBEBB,BE,reservefonds ACP Jupiter #0840.357.619
31,BE92 0882 7323 2423,08/07/2025,12,103,BE47 9733 9672 4980,NICULESCU - NICULESCU,AVENUE HENRI LIEBRECHT 88/3d r,1090 JETTE,VERSEMENT INSTANTANE DE BE47 9733 9672 4980 NI...,08/07/2025,"35,44",EUR,ARSPBE22,BE,+++515/9340/01329+++

In [3]:
df.columns

Index(['Compte', 'Date de comptabilisation', 'Numéro d'extrait',
       'Numéro de transaction', 'Compte contrepartie',
       'Nom contrepartie contient', 'Rue et numéro', 'Code postal et localité',
       'Transaction', 'Date valeur', 'Montant', 'Devise', 'BIC', 'Code pays',
       'Communications'],
      dtype='object')

In [4]:
df.drop(df.columns[[0, 1, 2, 3, 4, 6, 7, 8, 11, 12, 13]], axis = 1, inplace= True)
df.rename(columns={'Nom contrepartie contient': 'Contrepartie', 'Date valeur': 'Date'}, inplace = True)
df

,Contrepartie,Date,Montant,Communications
0,Dodevski - Dodevska,16/09/2025,"38,47",DODEVSKI DODEVSKA 07D G5
1,LAMAASSAB LOTFI,13/09/2025,"43,40",+++787/3088/12694+++
2,MACHIELS DANNY,10/09/2025,"43,40",reservefonds ACP Jupiter #0840.357.619
3,Mme Coumont Marie France,09/09/2025,"43,40",+++121/9258/59624+++
4,BADOT PIERRE,05/09/2025,"85,78",+++544/3098/07514+++
...,...,...,...,...
173,MATTELAER NICOLE,03/10/2024,"85,78",472/5733/42023
174,NaN,01/10/2024,"-58,46",PRECOMPTE MOBILIER SUR INTERETS ...
175,NaN,01/10/2024,"96,68",BONUS ...
176,NaN,01/10/2024,"98,17",INTERETS CREDITEURS ...
177,JUPITER BV,02/10/2024,"70,88",+++722/6400/01522+++

## Conversion de types

In [5]:
df.columns

Index(['Contrepartie', 'Date', 'Montant', 'Communications'], dtype='object')

In [6]:
df["Montant"] = df["Montant"].str.replace(',', '.')
df['Montant'] = pd.to_numeric(df['Montant'])
df['Date'] = pd.to_datetime(df['Date'], dayfirst = True, format="%d/%m/%Y" )
df

,Contrepartie,Date,Montant,Communications
0,Dodevski - Dodevska,2025-09-16,38.47,DODEVSKI DODEVSKA 07D G5
1,LAMAASSAB LOTFI,2025-09-13,43.40,+++787/3088/12694+++
2,MACHIELS DANNY,2025-09-10,43.40,reservefonds ACP Jupiter #0840.357.619
3,Mme Coumont Marie France,2025-09-09,43.40,+++121/9258/59624+++
4,BADOT PIERRE,2025-09-05,85.78,+++544/3098/07514+++
...,...,...,...,...
173,MATTELAER NICOLE,2024-10-03,85.78,472/5733/42023
174,NaN,2024-10-01,-58.46,PRECOMPTE MOBILIER SUR INTERETS ...
175,NaN,2024-10-01,96.68,BONUS ...
176,NaN,2024-10-01,98.17,INTERETS CREDITEURS ...
177,JUPITER BV,2024-10-02,70.88,+++722/6400/01522+++

## Suppression NaN

In [7]:
df.isna().any()

Contrepartie       True
Date              False
Montant           False
Communications     True
dtype: bool

In [8]:
df["Contrepartie"].isnull().sum()

np.int64(12)

In [9]:
df[df["Contrepartie"].isnull()]

,Contrepartie,Date,Montant,Communications
41,NaN,2025-07-01,-45.06,PRECOMPTE MOBILIER SUR INTERETS ...
42,NaN,2025-07-01,77.59,BONUS ...
43,NaN,2025-07-01,72.60,INTERETS CREDITEURS ...
87,NaN,2025-04-01,-59.41,PRECOMPTE MOBILIER SUR INTERETS ...
88,NaN,2025-04-01,102.11,BONUS ...
89,NaN,2025-04-01,95.92,INTERETS CREDITEURS ...
131,NaN,2025-01-01,-60.66,PRECOMPTE MOBILIER SUR INTERETS ...
132,NaN,2025-01-01,101.08,BONUS ...
133,NaN,2025-01-01,101.11,INTERETS CREDITEURS ...
174,NaN,2024-10-01,-58.46,PRECOMPTE MOBILIER SUR INTERETS ...
175,NaN,2024-10-01,96.68,BONUS ...
176,NaN,2024-10-01,98.17,INTERETS CREDITEURS ...

In [10]:
df[df["Communications"].isnull()]

                   Contrepartie       Date  Montant Communications
52   MOLDEREZ JEAN FRANCOIS EMI 2025-06-05    35.44            NaN
66   MOLDEREZ JEAN FRANCOIS EMI 2025-05-07    35.44            NaN
82   MOLDEREZ JEAN FRANCOIS EMI 2025-04-05    35.44            NaN
101  MOLDEREZ JEAN FRANCOIS EMI 2025-03-05    35.44            NaN
113  MOLDEREZ JEAN FRANCOIS EMI 2025-02-05    35.44            NaN
126  MOLDEREZ JEAN FRANCOIS EMI 2025-01-07    35.44            NaN
142  MOLDEREZ JEAN FRANCOIS EMI 2024-12-05    35.44            NaN
155  MOLDEREZ JEAN FRANCOIS EMI 2024-11-06    35.44            NaN
170  MOLDEREZ JEAN FRANCOIS EMI 2024-10-05    35.44            NaN

In [11]:
df.loc[df["Contrepartie"] == "MOLDEREZ JEAN FRANCOIS EMI", "Communications"] = "Charges"
df[df["Contrepartie"] == "MOLDEREZ JEAN FRANCOIS EMI"]

                   Contrepartie       Date  Montant Communications
5    MOLDEREZ JEAN FRANCOIS EMI 2025-09-05    35.00        Charges
19   MOLDEREZ JEAN FRANCOIS EMI 2025-08-06    35.00        Charges
34   MOLDEREZ JEAN FRANCOIS EMI 2025-07-05    35.00        Charges
52   MOLDEREZ JEAN FRANCOIS EMI 2025-06-05    35.44        Charges
66   MOLDEREZ JEAN FRANCOIS EMI 2025-05-07    35.44        Charges
82   MOLDEREZ JEAN FRANCOIS EMI 2025-04-05    35.44        Charges
101  MOLDEREZ JEAN FRANCOIS EMI 2025-03-05    35.44        Charges
113  MOLDEREZ JEAN FRANCOIS EMI 2025-02-05    35.44        Charges
126  MOLDEREZ JEAN FRANCOIS EMI 2025-01-07    35.44        Charges
142  MOLDEREZ JEAN FRANCOIS EMI 2024-12-05    35.44        Charges
155  MOLDEREZ JEAN FRANCOIS EMI 2024-11-06    35.44        Charges
170  MOLDEREZ JEAN FRANCOIS EMI 2024-10-05    35.44        Charges

In [12]:
df.isna().any()

Contrepartie       True
Date              False
Montant           False
Communications    False
dtype: bool

In [13]:
df.fillna("Belfius", inplace=True)
belfius = df[df["Contrepartie"] == "Belfius"]
belfius.shape[0]

12

## Séparation entre recettes et dépenses

In [14]:
rc = df[df['Montant'] > 0].iloc[:,:]  # iloc used to create a new dataframe
rc.shape[0]

174

In [15]:
dp = df[df['Montant'] < 0].iloc[:,:]
dp.shape[0]

4

## Vérification des dépenses
- Ajout d'une colonne "Justificatif ?" pour la présence d'une pièce justificative correspondant à la dépense (valeur initiale : False)
- Ajout d'une colonne "Commentaires" pour toute note complémentaire utile.

### Fonctions auxiliaires - Vérification des dépenses

In [16]:
def check_ok_montant(montant, commentaire, ok = True, df = dp):
  to_update = df['Montant'] == montant
  df.loc[to_update, 'Justificatif ?'] = ok
  df.loc[to_update, 'Commentaires'] = commentaire

def check_ok_contrepartie(contrepartie, commentaire = "Facture présente", ok = True, df = dp):
  df.loc[df["Contrepartie"] == contrepartie, "Commentaires"] = commentaire
  df.loc[df["Contrepartie"] == contrepartie, "Justificatif ?"] = ok

def check_ok_contreparties(*contreparties):
  for contrepartie in contreparties :
    check_ok_contrepartie(contrepartie)

### Total Dépenses

In [17]:
total_depenses = dp["Montant"].sum()
total_depenses

np.float64(-223.59)

### Nombre de lignes dépenses à traiter

In [18]:
a_traiter = dp.shape[0]
a_traiter

4

In [19]:
dp

,Contrepartie,Date,Montant,Communications
41,Belfius,2025-07-01,-45.06,PRECOMPTE MOBILIER SUR INTERETS ...
87,Belfius,2025-04-01,-59.41,PRECOMPTE MOBILIER SUR INTERETS ...
131,Belfius,2025-01-01,-60.66,PRECOMPTE MOBILIER SUR INTERETS ...
174,Belfius,2024-10-01,-58.46,PRECOMPTE MOBILIER SUR INTERETS ...

### Frais bancaires

In [20]:
check_ok_contrepartie("Belfius", "Frais bancaires")
belfius = dp[dp["Contrepartie"] == "Belfius"]
belfius

,Contrepartie,Date,Montant,Communications,Commentaires,Justificatif ?
41,Belfius,2025-07-01,-45.06,PRECOMPTE MOBILIER SUR INTERETS ...,Frais bancaires,True
87,Belfius,2025-04-01,-59.41,PRECOMPTE MOBILIER SUR INTERETS ...,Frais bancaires,True
131,Belfius,2025-01-01,-60.66,PRECOMPTE MOBILIER SUR INTERETS ...,Frais bancaires,True
174,Belfius,2024-10-01,-58.46,PRECOMPTE MOBILIER SUR INTERETS ...,Frais bancaires,True

In [21]:
a_traiter = a_traiter - belfius.shape[0]
a_traiter

0

#### Transfert interne

In [22]:
jupiter = dp[dp["Contrepartie"] == "ACP JUPITER"]
jupiter

Empty DataFrame
Columns: [Contrepartie, Date, Montant, Communications, Commentaires, Justificatif ?]
Index: []

##### Notes
- Ok : pas de transfert interne cette année

In [23]:
a_traiter = a_traiter - jupiter.shape[0]
a_traiter

0

## Vérification des recettes

In [24]:
rc.head()

,Contrepartie,Date,Montant,Communications
0,Dodevski - Dodevska,2025-09-16,38.47,DODEVSKI DODEVSKA 07D G5
1,LAMAASSAB LOTFI,2025-09-13,43.40,+++787/3088/12694+++
2,MACHIELS DANNY,2025-09-10,43.40,reservefonds ACP Jupiter #0840.357.619
3,Mme Coumont Marie France,2025-09-09,43.40,+++121/9258/59624+++
4,BADOT PIERRE,2025-09-05,85.78,+++544/3098/07514+++

### Total Recettes

In [25]:
total_recettes = rc["Montant"].sum()
total_recettes

np.float64(14365.6)

### Nombre de lignes recettes à traiter

In [26]:
a_traiter = rc.shape[0]
a_traiter

174

In [27]:
contreparties = rc["Contrepartie"].unique()
contreparties.sort()
contreparties

array(['ACP JUPITER', 'BADOT PIERRE', 'BOURGEOIS NANCY VALENTINE',
       'Belfius', 'Dodevski - Dodevska', 'JUPITER BV', 'LAMAASSAB LOTFI',
       'LEFEVRE NICOLAS', 'MACHIELS DANNY', 'MAIGRET-PAILOS FERNANDEZ',
       'MATTELAER NICOLE', 'MOLDEREZ JEAN FRANCOIS EMI',
       'Mme Coumont Marie France', 'NICULESCU - NICULESCU',
       'Raveyts Annie', 'Vanvulescu Causette'], dtype=object)

In [28]:
contreparties.size

16

In [29]:
rc.loc[rc["Contrepartie"].isin(["Dodevski - Dodevska", "Dodevski Dragan"]), "Contrepartie"] = "Dodevski"
rc.loc[rc["Contrepartie"].isin(["MAIGRET CHRISTIAN JACQUES", "MAIGRET-PAILOS FERNANDEZ"]), "Contrepartie"] = "MAIGRET"
rc.loc[rc["Contrepartie"].isin(["NICULESCU - NICULESCU"]), "Contrepartie"] = "Niculescu"
contreparties = rc["Contrepartie"].unique()
contreparties.sort()
contreparties

array(['ACP JUPITER', 'BADOT PIERRE', 'BOURGEOIS NANCY VALENTINE',
       'Belfius', 'Dodevski', 'JUPITER BV', 'LAMAASSAB LOTFI',
       'LEFEVRE NICOLAS', 'MACHIELS DANNY', 'MAIGRET', 'MATTELAER NICOLE',
       'MOLDEREZ JEAN FRANCOIS EMI', 'Mme Coumont Marie France',
       'Niculescu', 'Raveyts Annie', 'Vanvulescu Causette'], dtype=object)

In [30]:
contreparties.size

16

In [31]:
rc[~rc["Contrepartie"].isin(['BADOT PIERRE', 'BOURGEOIS NANCY VALENTINE', 'Belfius', 'Dodevski',
       'JELLAB ABDELMAJID', 'JUPITER BV', 'LAMAASSAB LOTFI',
       'LEFEVRE NICOLAS', 'MACHIELS DANNY', 'MAIGRET', 'MATTELAER NICOLE',
       'MOLDEREZ JEAN FRANCOIS EMI', 'Mme Coumont Marie France',
       'Niculescu', 'Raveyts Annie', 'Vanvulescu Causette'])]

   Contrepartie       Date  Montant Communications
59  ACP JUPITER 2025-05-27   5600.0    tft interne

In [32]:
rc.shape[0]

174

In [33]:
reste = rc.copy(deep=True)
reste.shape[0]

174

#### 1. BADOT PIERRE

In [34]:
badot = rc[rc["Contrepartie"] == "BADOT PIERRE"]
badot

     Contrepartie       Date  Montant        Communications
4    BADOT PIERRE 2025-09-05    85.78  +++544/3098/07514+++
21   BADOT PIERRE 2025-08-05    85.78  +++544/3098/07514+++
33   BADOT PIERRE 2025-07-05    85.78  +++544/3098/07514+++
50   BADOT PIERRE 2025-06-05    85.78  +++544/3098/07514+++
67   BADOT PIERRE 2025-05-06    85.78  +++544/3098/07514+++
81   BADOT PIERRE 2025-04-05    85.78  +++544/3098/07514+++
98   BADOT PIERRE 2025-03-05    85.78  +++544/3098/07514+++
112  BADOT PIERRE 2025-02-05    85.78  +++544/3098/07514+++
125  BADOT PIERRE 2025-01-07    85.78  +++544/3098/07514+++
141  BADOT PIERRE 2024-12-05    85.78  +++544/3098/07514+++
156  BADOT PIERRE 2024-11-05    85.78  +++544/3098/07514+++
168  BADOT PIERRE 2024-10-05    85.78  +++544/3098/07514+++

In [35]:
a_traiter = a_traiter - badot.shape[0]
a_traiter

162

In [36]:
reste = reste.loc[reste["Contrepartie"] != "BADOT PIERRE"]
reste.shape[0]

162

#### 2. BOURGEOIS NANCY VALENTINE

In [37]:
bourgeois = rc[rc["Contrepartie"] == "BOURGEOIS NANCY VALENTINE"]
bourgeois

                  Contrepartie       Date  Montant        Communications
9    BOURGEOIS NANCY VALENTINE 2025-09-03    35.44  +++964/8104/47052+++
22   BOURGEOIS NANCY VALENTINE 2025-08-05    35.44  +++964/8104/47052+++
37   BOURGEOIS NANCY VALENTINE 2025-07-03    35.44  +++964/8104/47052+++
54   BOURGEOIS NANCY VALENTINE 2025-06-04    35.44  +++964/8104/47052+++
69   BOURGEOIS NANCY VALENTINE 2025-05-06    35.44  +++964/8104/47052+++
79   BOURGEOIS NANCY VALENTINE 2025-04-09    35.44  +++964/8104/47052+++
95   BOURGEOIS NANCY VALENTINE 2025-03-07    35.44  +++964/8104/47052+++
111  BOURGEOIS NANCY VALENTINE 2025-02-07    35.44  +++964/8104/47052+++
124  BOURGEOIS NANCY VALENTINE 2025-01-08    35.44  +++964/8104/47052+++
138  BOURGEOIS NANCY VALENTINE 2024-12-07    35.44  +++964/8104/47052+++
153  BOURGEOIS NANCY VALENTINE 2024-11-07    35.44  +++964/8104/47052+++
166  BOURGEOIS NANCY VALENTINE 2024-10-09    35.44  +++964/8104/47052+++

In [38]:
a_traiter = a_traiter - bourgeois.shape[0]
a_traiter

150

In [39]:
reste = reste.loc[reste["Contrepartie"] != "BOURGEOIS NANCY VALENTINE"]
reste.shape[0]

150

#### 3. Belfius

In [40]:
belfius = rc[rc["Contrepartie"] == "Belfius"]
belfius

,Contrepartie,Date,Montant,Communications
42,Belfius,2025-07-01,77.59,BONUS ...
43,Belfius,2025-07-01,72.60,INTERETS CREDITEURS ...
88,Belfius,2025-04-01,102.11,BONUS ...
89,Belfius,2025-04-01,95.92,INTERETS CREDITEURS ...
132,Belfius,2025-01-01,101.08,BONUS ...
133,Belfius,2025-01-01,101.11,INTERETS CREDITEURS ...
175,Belfius,2024-10-01,96.68,BONUS ...
176,Belfius,2024-10-01,98.17,INTERETS CREDITEURS ...

In [41]:
belfius_interets = belfius["Montant"].sum()
belfius_interets

np.float64(745.26)

In [42]:
a_traiter = a_traiter - belfius.shape[0]
a_traiter

142

In [43]:
reste = reste.loc[reste["Contrepartie"] != "Belfius"]
reste.shape[0]

142

#### 4. Dodevski

In [44]:
dodevski = rc[rc["Contrepartie"] == "Dodevski"]
dodevski

    Contrepartie       Date  Montant             Communications
0       Dodevski 2025-09-16    38.47   DODEVSKI DODEVSKA 07D G5
14      Dodevski 2025-08-18    38.47   DIDEVSKI DODEVSKA 07D G5
28      Dodevski 2025-07-15    38.47  DODEVSKI DODEVSKA 7DR 05G
45      Dodevski 2025-06-24    38.47     DodevskiDodevska07D G5
61      Dodevski 2025-05-17    38.47    DodevskiDodevska 07D G5
75      Dodevski 2025-04-14    38.47    Dodevski Dodevska07D G5
91      Dodevski 2025-03-13    38.47   Dodevski Dodevska 07D G5
105     Dodevski 2025-02-22    38.47   Dodevski Dodevska 07D G5
118     Dodevski 2025-02-02    38.47    Dodevsk Dodevska 07D G5
134     Dodevski 2024-12-13    38.47    DodevskiDodevska 07D G5
149     Dodevski 2024-11-12    38.47    DodevskiDodevska 07D G5
164     Dodevski 2024-10-09    38.47   DodevskiDodevska A07D G5

In [45]:
a_traiter = a_traiter - dodevski.shape[0]
a_traiter

130

In [46]:
reste = reste.loc[reste["Contrepartie"] != "Dodevski"]
reste.shape[0]

130

#### 6. JUPITER BV

In [47]:
jupiter = rc[rc["Contrepartie"] == "JUPITER BV"]
jupiter

    Contrepartie       Date  Montant        Communications
13    JUPITER BV 2025-09-02    70.88  +++722/6400/01522+++
27    JUPITER BV 2025-08-02    70.88  +++722/6400/01522+++
44    JUPITER BV 2025-07-02    70.88  +++722/6400/01522+++
57    JUPITER BV 2025-06-03    70.88  +++722/6400/01522+++
72    JUPITER BV 2025-05-03    70.88  +++722/6400/01522+++
90    JUPITER BV 2025-04-02    70.88  +++722/6400/01522+++
102   JUPITER BV 2025-03-04    70.88  +++722/6400/01522+++
115   JUPITER BV 2025-02-04    70.88  +++722/6400/01522+++
129   JUPITER BV 2025-01-03    70.88  +++722/6400/01522+++
145   JUPITER BV 2024-12-03    70.88  +++722/6400/01522+++
161   JUPITER BV 2024-11-02    70.88  +++722/6400/01522+++
177   JUPITER BV 2024-10-02    70.88  +++722/6400/01522+++

In [48]:
a_traiter = a_traiter - jupiter.shape[0]
a_traiter

118

In [49]:
reste = reste.loc[reste["Contrepartie"] != "JUPITER BV"]
reste.shape[0]

118

#### 7. LAMAASSAB LOTFI

In [50]:
lotfi = rc[rc["Contrepartie"] == "LAMAASSAB LOTFI"]
lotfi

        Contrepartie       Date  Montant        Communications
1    LAMAASSAB LOTFI 2025-09-13     43.4  +++787/3088/12694+++
15   LAMAASSAB LOTFI 2025-08-13     43.4  +++787/3088/12694+++
29   LAMAASSAB LOTFI 2025-07-15     43.4  +++787/3088/12694+++
46   LAMAASSAB LOTFI 2025-06-13     43.4  +++787/3088/12694+++
62   LAMAASSAB LOTFI 2025-05-14     43.4  +++787/3088/12694+++
74   LAMAASSAB LOTFI 2025-04-15     43.4  +++787/3088/12694+++
92   LAMAASSAB LOTFI 2025-03-13     43.4  +++787/3088/12694+++
106  LAMAASSAB LOTFI 2025-02-13     43.4  +++787/3088/12694+++
119  LAMAASSAB LOTFI 2025-01-15     43.4  +++787/3088/12694+++
135  LAMAASSAB LOTFI 2024-12-13     43.4  +++787/3088/12694+++
148  LAMAASSAB LOTFI 2024-11-13     43.4  +++787/3088/12694+++
162  LAMAASSAB LOTFI 2024-10-15     43.4  +++787/3088/12694+++

In [51]:
a_traiter = a_traiter - lotfi.shape[0]
a_traiter

106

In [52]:
reste = reste.loc[reste["Contrepartie"] != "LAMAASSAB LOTFI"]
reste.shape[0]

106

#### 8. LEFEVRE NICOLAS

In [53]:
lefevre = rc[rc["Contrepartie"] == "LEFEVRE NICOLAS"]
lefevre

        Contrepartie       Date  Montant        Communications
12   LEFEVRE NICOLAS 2025-09-01    31.42          609724853733
23   LEFEVRE NICOLAS 2025-08-05    31.42  +++609/7248/53733+++
36   LEFEVRE NICOLAS 2025-07-02    31.42          609724853733
49   LEFEVRE NICOLAS 2025-06-06    31.42  +++609/7248/53733+++
60   LEFEVRE NICOLAS 2025-05-17    31.42          609724853733
76   LEFEVRE NICOLAS 2025-04-12    31.42          609724853733
100  LEFEVRE NICOLAS 2025-03-05    94.26  +++609/7248/53733+++
139  LEFEVRE NICOLAS 2024-12-05    31.42          609724853733
151  LEFEVRE NICOLAS 2024-11-09    31.42          609724853733

In [54]:
a_traiter = a_traiter - lefevre.shape[0]
a_traiter

97

In [55]:
reste = reste.loc[reste["Contrepartie"] != "LEFEVRE NICOLAS"]
reste.shape[0]

97

#### 9. MACHIELS DANNY

In [56]:
danny = rc[rc["Contrepartie"] == "MACHIELS DANNY"]
danny

,Contrepartie,Date,Montant,Communications
2,MACHIELS DANNY,2025-09-10,43.4,reservefonds ACP Jupiter #0840.357.619
16,MACHIELS DANNY,2025-08-12,43.4,reservefonds ACP Jupiter #0840.357.619
30,MACHIELS DANNY,2025-07-10,43.4,reservefonds ACP Jupiter #0840.357.619
47,MACHIELS DANNY,2025-06-10,43.4,reservefonds ACP Jupiter #0840.357.619
63,MACHIELS DANNY,2025-05-10,43.4,reservefonds ACP Jupiter #0840.357.619
77,MACHIELS DANNY,2025-04-10,43.4,reservefonds ACP Jupiter #0840.357.619
93,MACHIELS DANNY,2025-03-11,43.4,reservefonds ACP Jupiter #0840.357.619
107,MACHIELS DANNY,2025-02-11,43.4,reservefonds ACP Jupiter #0840.357.619
121,MACHIELS DANNY,2025-01-10,43.4,reservefonds ACP Jupiter #0840.357.619
136,MACHIELS DANNY,2024-12-10,43.4,reservefonds ACP Jupiter #0840.357.619
150,MACHIELS DANNY,2024-11-12,43.4,reservefonds ACP Jupiter #0840.357.619
163,MACHIELS DANNY,2024-10-10,43.4,reservefonds ACP Jupiter #0840.357.619

In [57]:
a_traiter = a_traiter - danny.shape[0]
a_traiter

85

In [58]:
reste = reste.loc[reste["Contrepartie"] != "MACHIELS DANNY"]
reste.shape[0]

85

#### 10. MAIGRET

In [59]:
maigret = rc[rc["Contrepartie"] == "MAIGRET"]
maigret

    Contrepartie       Date  Montant        Communications
10       MAIGRET 2025-09-03     43.4  +++381/2316/20589+++
24       MAIGRET 2025-08-05     43.4  +++381/2316/20589+++
38       MAIGRET 2025-07-03     43.4  +++381/2316/20589+++
53       MAIGRET 2025-06-04     43.4  +++381/2316/20589+++
68       MAIGRET 2025-05-06     43.4  +++381/2316/20589+++
85       MAIGRET 2025-04-03     43.4  +++381/2316/20589+++
99       MAIGRET 2025-03-05     43.4  +++381/2316/20589+++
114      MAIGRET 2025-02-05     43.4  +++381/2316/20589+++
123      MAIGRET 2025-01-08     43.4  +++381/2316/20589+++
143      MAIGRET 2024-12-04     43.4  +++381/2316/20589+++
158      MAIGRET 2024-11-05     43.4  +++381/2316/20589+++
172      MAIGRET 2024-10-03     43.4  +++381/2316/20589+++

In [60]:
a_traiter = a_traiter - maigret.shape[0]
a_traiter

73

In [61]:
reste = reste.loc[reste["Contrepartie"] != "MAIGRET"]
reste.shape[0]

73

#### 11. MATTELAER NICOLE

In [62]:
nicole = rc[rc["Contrepartie"] == "MATTELAER NICOLE"]
nicole

         Contrepartie       Date  Montant  Communications
11   MATTELAER NICOLE 2025-09-03    85.78  472/5733/42023
26   MATTELAER NICOLE 2025-08-05    85.78  472/5733/42023
39   MATTELAER NICOLE 2025-07-03    85.78  472/5733/42023
58   MATTELAER NICOLE 2025-06-03    85.78  472/5733/42023
73   MATTELAER NICOLE 2025-05-03    85.78  472/5733/42023
86   MATTELAER NICOLE 2025-04-03    85.78  472/5733/42023
103  MATTELAER NICOLE 2025-03-04    85.78  472/5733/42023
116  MATTELAER NICOLE 2025-02-04    85.78  472/5733/42023
130  MATTELAER NICOLE 2025-01-03    85.78  472/5733/42023
146  MATTELAER NICOLE 2024-12-03    85.78  472/5733/42023
160  MATTELAER NICOLE 2024-11-05    85.78  472/5733/42023
173  MATTELAER NICOLE 2024-10-03    85.78  472/5733/42023

In [63]:
a_traiter = a_traiter - nicole.shape[0]
a_traiter

61

In [64]:
reste = reste.loc[reste["Contrepartie"] != "MATTELAER NICOLE"]
reste.shape[0]

61

#### 12. MOLDEREZ JEAN FRANCOIS EMI

In [65]:
jf = rc[rc["Contrepartie"] == "MOLDEREZ JEAN FRANCOIS EMI"]
jf

                   Contrepartie       Date  Montant Communications
5    MOLDEREZ JEAN FRANCOIS EMI 2025-09-05    35.00        Charges
19   MOLDEREZ JEAN FRANCOIS EMI 2025-08-06    35.00        Charges
34   MOLDEREZ JEAN FRANCOIS EMI 2025-07-05    35.00        Charges
52   MOLDEREZ JEAN FRANCOIS EMI 2025-06-05    35.44        Charges
66   MOLDEREZ JEAN FRANCOIS EMI 2025-05-07    35.44        Charges
82   MOLDEREZ JEAN FRANCOIS EMI 2025-04-05    35.44        Charges
101  MOLDEREZ JEAN FRANCOIS EMI 2025-03-05    35.44        Charges
113  MOLDEREZ JEAN FRANCOIS EMI 2025-02-05    35.44        Charges
126  MOLDEREZ JEAN FRANCOIS EMI 2025-01-07    35.44        Charges
142  MOLDEREZ JEAN FRANCOIS EMI 2024-12-05    35.44        Charges
155  MOLDEREZ JEAN FRANCOIS EMI 2024-11-06    35.44        Charges
170  MOLDEREZ JEAN FRANCOIS EMI 2024-10-05    35.44        Charges

In [66]:
a_traiter = a_traiter - jf.shape[0]
a_traiter

49

In [67]:
reste = reste.loc[reste["Contrepartie"] != "MOLDEREZ JEAN FRANCOIS EMI"]
reste.shape[0]

49

#### 13. Mme Coumont Marie France

In [68]:
mf = rc[rc["Contrepartie"] == "Mme Coumont Marie France"]
mf

                 Contrepartie       Date  Montant        Communications
3    Mme Coumont Marie France 2025-09-09     43.4  +++121/9258/59624+++
18   Mme Coumont Marie France 2025-08-07     43.4  +++121/9258/59624+++
32   Mme Coumont Marie France 2025-07-09     43.4  +++121/9258/59624+++
48   Mme Coumont Marie France 2025-06-07     43.4  +++121/9258/59624+++
65   Mme Coumont Marie France 2025-05-07     43.4  +++121/9258/59624+++
78   Mme Coumont Marie France 2025-04-09     43.4  +++121/9258/59624+++
94   Mme Coumont Marie France 2025-03-07     43.4  +++121/9258/59624+++
109  Mme Coumont Marie France 2025-02-07     43.4  +++121/9258/59624+++
122  Mme Coumont Marie France 2025-01-08     43.4  +++121/9258/59624+++
137  Mme Coumont Marie France 2024-12-07     43.4  +++121/9258/59624+++
154  Mme Coumont Marie France 2024-11-07     43.4  +++121/9258/59624+++
165  Mme Coumont Marie France 2024-10-09     43.4  +++121/9258/59624+++

In [69]:
a_traiter = a_traiter - mf.shape[0]
a_traiter

37

In [70]:
reste = reste.loc[reste["Contrepartie"] != "Mme Coumont Marie France"]
reste.shape[0]

37

#### 14. Niculescu

In [71]:
nic = rc[rc["Contrepartie"] == "Niculescu"]
nic

    Contrepartie       Date  Montant        Communications
6      Niculescu 2025-09-03    35.44  +++515/9340/01329+++
17     Niculescu 2025-08-06    35.44  +++515/9340/01329+++
31     Niculescu 2025-07-08    35.44  +++515/9340/01329+++
51     Niculescu 2025-06-04    35.44  +++515/9340/01329+++
64     Niculescu 2025-05-07    35.44  +++515/9340/01329+++
80     Niculescu 2025-04-04    35.44  +++515/9340/01329+++
96     Niculescu 2025-03-05    35.44  +++515/9340/01329+++
108    Niculescu 2025-02-08    35.44  +++515/9340/01329+++
120    Niculescu 2025-01-09    35.44  +++515/9340/01329+++
140    Niculescu 2024-12-04    35.44  +++515/9340/01329+++
152    Niculescu 2024-11-06    35.44  +++515/9340/01329+++
169    Niculescu 2024-10-04    35.44  +++515/9340/01329+++

In [72]:
a_traiter = a_traiter - nic.shape[0]
a_traiter

25

In [73]:
reste = reste.loc[reste["Contrepartie"] != "Niculescu"]
reste.shape[0]

25

#### 15. Raveyts Annie

In [74]:
raveyts = rc[rc["Contrepartie"] == "Raveyts Annie"]
raveyts

      Contrepartie       Date  Montant        Communications
7    Raveyts Annie 2025-09-04    35.44  +++174/8037/33241+++
25   Raveyts Annie 2025-08-05    35.44  +++174/8037/33241+++
35   Raveyts Annie 2025-07-04    35.44  +++174/8037/33241+++
55   Raveyts Annie 2025-06-04    35.44  +++174/8037/33241+++
70   Raveyts Annie 2025-05-06    35.44  +++174/8037/33241+++
84   Raveyts Annie 2025-04-04    35.44  +++174/8037/33241+++
104  Raveyts Annie 2025-03-04    35.44  +++174/8037/33241+++
117  Raveyts Annie 2025-02-04    35.44  +++174/8037/33241+++
127  Raveyts Annie 2025-01-04    35.44  +++174/8037/33241+++
144  Raveyts Annie 2024-12-04    35.44  +++174/8037/33241+++
159  Raveyts Annie 2024-11-05    35.44  +++174/8037/33241+++
171  Raveyts Annie 2024-10-04    35.44  +++174/8037/33241+++

In [75]:
a_traiter = a_traiter - raveyts.shape[0]
a_traiter

13

In [76]:
reste = reste.loc[reste["Contrepartie"] != "Raveyts Annie"]
reste.shape[0]

13

#### 16. Vanvulescu Causette

In [77]:
cosette = rc[rc["Contrepartie"] == "Vanvulescu Causette"]
cosette

            Contrepartie       Date  Montant        Communications
8    Vanvulescu Causette 2025-09-02     43.4  +++523/3226/76235+++
20   Vanvulescu Causette 2025-08-04     43.4  +++523/3226/76235+++
40   Vanvulescu Causette 2025-07-01     43.4  +++523/3226/76235+++
56   Vanvulescu Causette 2025-06-03     43.4  +++523/3226/76235+++
71   Vanvulescu Causette 2025-05-03     43.4  +++523/3226/76235+++
83   Vanvulescu Causette 2025-04-04     43.4  +++523/3226/76235+++
97   Vanvulescu Causette 2025-03-05     43.4  +++523/3226/76235+++
110  Vanvulescu Causette 2025-02-07     43.4  +++523/3226/76235+++
128  Vanvulescu Causette 2025-01-03     43.4  +++523/3226/76235+++
147  Vanvulescu Causette 2024-12-02     43.4  +++523/3226/76235+++
157  Vanvulescu Causette 2024-11-05     43.4  +++523/3226/76235+++
167  Vanvulescu Causette 2024-10-06     43.4  +++523/3226/76235+++

In [78]:
a_traiter = a_traiter - cosette.shape[0]
a_traiter

1

In [79]:
reste = reste.loc[reste["Contrepartie"] != "Vanvulescu Causette"]
reste.shape[0]

1

In [80]:
reste

   Contrepartie       Date  Montant Communications
59  ACP JUPITER 2025-05-27   5600.0    tft interne

## Compte Réserve 2023-2024
- Solde au 30/09/2024 : 71802,18 €
- Total dépenses : 5811,4 € dont transfert interne de 5600 € et frais bancaires de 211.4 €
- Total recettes : 11196.28 € dont intérêts de 704,66 €